//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashback.Domain {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cashback.Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF informado é inválido..
        /// </summary>
        public static string CPFInvalid {
            get {
                return ResourceManager.GetString("CPFInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O e-mail informado é inválido..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível acessar a API externa..
        /// </summary>
        public static string ErrorOnAccessExternalAPI {
            get {
                return ResourceManager.GetString("ErrorOnAccessExternalAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível converter os dados da API Externa..
        /// </summary>
        public static string ErrorOnConvertResult {
            get {
                return ResourceManager.GetString("ErrorOnConvertResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login ou senha inválidos..
        /// </summary>
        public static string LoginOrPassInvalid {
            get {
                return ResourceManager.GetString("LoginOrPassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome é obrigatório..
        /// </summary>
        public static string NameIsObrigatory {
            get {
                return ResourceManager.GetString("NameIsObrigatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome deve ter no máximo 100 caracteres..
        /// </summary>
        public static string NameShouldBeLessThan100Chars {
            get {
                return ResourceManager.GetString("NameShouldBeLessThan100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem dados para validar ou inserir..
        /// </summary>
        public static string NullObject {
            get {
                return ResourceManager.GetString("NullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha é obrigatória..
        /// </summary>
        public static string PasswordIsObrigatory {
            get {
                return ResourceManager.GetString("PasswordIsObrigatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor da compra deve ser maior que 0..
        /// </summary>
        public static string PurchaseValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PurchaseValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um(a) revendedor(a) com o CPF informado..
        /// </summary>
        public static string ResellerCPFInUse {
            get {
                return ResourceManager.GetString("ResellerCPFInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF do(a) revendedor(a) é inválido..
        /// </summary>
        public static string ResellerCPFInvalid {
            get {
                return ResourceManager.GetString("ResellerCPFInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um(a) revendedor(a) com o Email informado..
        /// </summary>
        public static string ResellerEmailInUse {
            get {
                return ResourceManager.GetString("ResellerEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum(a) revendedor(a) encontrado(a) com o CPF informado..
        /// </summary>
        public static string ResellerNotFoundByCPF {
            get {
                return ResourceManager.GetString("ResellerNotFoundByCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aprovado.
        /// </summary>
        public static string TextApprovedStatusPurchaseOrder {
            get {
                return ResourceManager.GetString("TextApprovedStatusPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Em análise.
        /// </summary>
        public static string TextWaitingApprovalStatusPurchaseOrder {
            get {
                return ResourceManager.GetString("TextWaitingApprovalStatusPurchaseOrder", resourceCulture);
            }
        }
    }
}
