// <auto-generated />
using System;
using Cashback.Infra.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cashback.Infra.Repository.Migrations
{
    [DbContext(typeof(PrincipalContext))]
    [Migration("20200905022039_Reseller")]
    partial class Reseller
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cashback.Domain.Entities.Reseller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoApproved")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("CHAR(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(64)");

                    b.HasKey("Id");

                    b.ToTable("Reselers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f72550c-5bc6-48bd-bc9c-178e7f559d7c"),
                            AutoApproved = true,
                            CPF = "153.509.460-56",
                            Email = "15350946056@teste.com.br",
                            Name = "Usuário [153.509.460-56]",
                            Password = "5o+mGdBwgsYcaGB4NGW5sVvFuYQ2+v+vLp5xQWkNAuQ="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
